.env:
  directory: ./
  filename: .env
  ignoreIfMalformed: true
  ignoreIfMissing: true
  systemProperties: true
  prefix: ""

spring:
  application:
    name: user-profile-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/user-profile-service}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL:update}

  kafka:
    properties:
      schema.registry.url: ${SCHEMA_REGISTRY:http://localhost:8081}
    bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:9092}

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
kafka:
  topic:
    application-review: user-profile-application-reviewed
    notification: notification
    csr:
      request: csr-request
      reply: csr-reply